- name: uninstall system ruby
  apt: name=ruby state=absent purge=yes
  become: yes

- name: add repository
  apt_repository: repo="{{ ruby_ppa }}" update_cache=yes
  become: yes

- name: install
  apt: name={{ item }} state=latest
  with_items:
    - "ruby{{ ruby_version }}"
    - "ruby{{ ruby_version }}-dev"
  become: yes

- name: install bundler
  gem: name=bundler user_install=no state=latest
  become: yes
